# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - PenguFamilyOfficial

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_619bb298c6a24572a25b77ad68fc663e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_50d3ee1cc06c4af78a203072905b3e6c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_619bb298c6a24572a25b77ad68fc663e }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PenguFamilyOfficial'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_62fa5766e2dd4fe29e5e0da8a68f80a8 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_619bb298c6a24572a25b77ad68fc663e }}/appsvc/staticsite:${{ github.sha }}'